# Generated by Django 3.1.5 on 2022-03-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20220303_2215'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
