# Generated by Django 3.1.5 on 2022-03-03 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ManyToManyField(to='browse.Category'),
        ),
        migrations.AlterField(
            model_name='restaurant_detail',
            name='category',
            field=models.ManyToManyField(to='browse.Category'),
        ),
    ]
