# Generated by Django 3.1.5 on 2022-03-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20220303_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
