# Generated by Django 3.1.5 on 2022-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_auto_20220311_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_detail',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
