# Generated by Django 3.1.5 on 2022-03-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Received', 'Order Received'), ('Cooking', 'Cooking'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Order Cancelled', 'Order Cancelled')], default='Pending', max_length=150),
        ),
    ]
