# Generated by Django 3.1.5 on 2022-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderDetail', '0002_auto_20220307_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status1',
            field=models.JSONField(default=dict),
        ),
    ]
