# Generated by Django 3.1.5 on 2022-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderDetail', '0003_order_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status1',
            field=models.JSONField(default=[]),
        ),
    ]
