# Generated by Django 3.1.5 on 2022-03-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderDetail', '0004_auto_20220312_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status1',
            field=models.JSONField(default=dict),
        ),
    ]
